baseurl = "https://ivalab.github.io/BioLoco/public/"
baseURL = "https://ivalab.github.io/BioLoco/public/"
title = "BioLoco Research"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
defaultContentLanguage = "en-us"
disqusShortname = ""
googleAnalytics = ""

[params]
  style = "sea"
  title = "IVALab:BioLoco"
  description = "Research efforts related to biologically-inspired locomotion."
  copyright = ""
  support = "Research supported in part by National Science Foundation.  Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation."
  sidebarAbout = [ "Research efforts related to controlled locomotion of undulatory bio-inspired robots (snakes, salamanders, and related)." ]


  [[params.grants]]
  grantee = "NSF"
  award = "1400256"
  url = "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1400256&HistoricalAwards=false"

  [[params.grants]]
  grantee = "NSF"
  award = "1562911"
  url = "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1562911&HistoricalAwards=false"

  [[params.navlinks]]
  name = "About"
  url = "about/"
  home = false

  [[params.navlinks]]
  name = "Robots"
  url  = "robots/"
  home = false

  [[params.navlinks]]
  name = "Research"
  url  = "research/"
  home = true

  [params.social]
  github  = "https://github.com/ivalab"
  github2  = "https://github.com/ivaROS"
  youtube = "https://www.youtube.com/channel/UCKQ7FxpjoK-1l3Bp2qXCiYw/"

[taxonomies]
  tags = "tags"
