baseurl = "https://ivalab.github.io/BioLoco/public"
title = "IVALab: BioLoco Research"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = ""


[params]
  style = "sea"
  description = "Research efforts related to biologically-inspired locomotion."
  copyright = ""
  sidebarAbout = [ "Test" ]


  [[params.navlinks]]
  name = "Home"
  url  = "research/"
  home = true


  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  github  = "https://github.com/ivalab"
  github2  = "https://github.com/ivaROS"
  youtube = "https://www.youtube.com/channel/UCKQ7FxpjoK-1l3Bp2qXCiYw/"
